FROM nixos/nix:latest

# The echo commands tell you where you're at, but also allow you
# to force a rebuild by changing the number displayed.

RUN echo A2 ; nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use mukn

#BUN echo B0 ; nix-env -f https://github.com/obsidiansystems/nix-thunk/archive/master.tar.gz -iA command

RUN echo C2 ; \
  mkdir -p /root/.config/nix && \
  (echo substituters = https://cache.nixos.org https://hydra.iohk.io https://iohk.cachix.org https://hydra.goguen-ala-cardano.dev-mantis.iohkdev.io https://cache.nixos.org/ https://mukn.cachix.org ; \
  echo trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= hydra.goguen-ala-cardano.dev-mantis.iohkdev.io-1:wh2Nepc/RGAY2UMvY5ugsT8JOz84BKLIpFbn7beZ/mo= mukn.cachix.org-1:ujoZLZMpGNQMeZbLBxmOcO7aj+7E5XSnZxwFpuhhsqs= \
  ) > /root/.config/nix/nix.conf

RUN echo D2 ; nix-env -f https://github.com/fare-patches/nixpkgs/archive/fare.tar.gz -iA go-ethereum solc racket zsh su screen less git openssh xz bashInteractive

RUN echo E2 ; nix-env -f https://github.com/fare-patches/nixpkgs/archive/fare.tar.gz -iA gerbil-unstable

ENV GAMBOPT t8,f8,-8,i8,dRr
ENV GERBIL_LOADPATH /root/.nix-profile/gerbil/lib

RUN echo F2 ; nix-env -f https://github.com/fare-patches/nixpkgs/archive/fare.tar.gz -iA gerbilPackages-unstable
